---

# Application settings.
virtualenv_root: "/webapps/.virtualenvs"
virtualenv_path: "{{ virtualenv_root }}/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn.log"
requirements_file: "{{ project_path }}/requirements/{{ env }}.txt"
django_settings_file: "config.settings.{{ env }}"

# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
gunicorn_access_log_file: "{{ application_log_dir }}/gunicorn_access.log"
gunicorn_error_log_file: "{{ application_log_dir }}/gunicorn_error.log"


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"
nginx_media_dir: "{{ project_path }}/media/"
