# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 18:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variety', models.CharField(choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')],
                                             max_length=255)),
                ('category', models.CharField(
                    choices=[('flower', 'Flower'), ('edible', 'Edible'), ('liquid', 'Liquid'), ('oil', 'Oil'),
                             ('wax', 'Wax')], max_length=255)),
                ('effects', django.contrib.postgres.fields.jsonb.JSONField(
                    default={'creative': 0, 'energetic': 0, 'euphoric': 0, 'focused': 0, 'good_humored': 0, 'happy': 0,
                             'hungry': 0, 'relaxed': 0, 'sleepy': 0, 'stimulated': 0, 'talkative': 0, 'tingly': 0,
                             'uplifted': 0})),
                ('benefits', django.contrib.postgres.fields.jsonb.JSONField(
                    default={'help_depression': 0, 'help_muscles_spasms': 0, 'help_with_insomnia': 0,
                             'help_with_seizures': 0, 'lower_eye_pressure': 0, 'reduce_fatigue': 0,
                             'reduce_headaches': 0, 'reduce_inflammation': 0, 'reduce_nausea': 0, 'reduce_stress': 0,
                             'relieve_cramps': 0, 'relieve_pain': 0, 'restore_appetite': 0})),
                ('side_effects', django.contrib.postgres.fields.jsonb.JSONField(
                    default={'anxiety': 0, 'dizziness': 0, 'dry_eyes': 0, 'dry_mouth': 0, 'headache': 0,
                             'paranoia': 0})),
                ('flavor', django.contrib.postgres.fields.jsonb.JSONField(
                    default={'ammonia': 0, 'apple': 0, 'apricot': 0, 'berry': 0, 'blue_cheese': 0, 'blueberry': 0,
                             'buttery': 0, 'cheese': 0, 'chemical': 0, 'chestnut': 0, 'citrus': 0, 'coffee': 0,
                             'diesel': 0, 'earthy': 0, 'flowery': 0, 'grape': 0, 'grapefruit': 0, 'herbal': 0,
                             'honey': 0, 'lavender': 0, 'lemon': 0, 'lime': 0, 'mango': 0, 'mentol': 0, 'minty': 0,
                             'nutty': 0, 'orange': 0, 'peach': 0, 'pear': 0, 'pepper': 0, 'pine': 0, 'pineapple': 0,
                             'plum': 0, 'pungent': 0, 'rose': 0, 'sage': 0, 'skunk': 0, 'spicy_herbal': 0,
                             'strawberry': 0, 'sweet': 0, 'tar': 0, 'tea': 0, 'tobacco': 0, 'tree_fruit': 0,
                             'tropical': 0, 'vanilla': 0, 'violet': 0, 'woody': 0})),
                ('origins', models.ManyToManyField(blank=True, to='search.Strain')),
            ],
        ),
    ]
