# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='about',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
