# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0002_strain_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='internal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
