# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0004_auto_20161006_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together=set([('name', 'category')]),
        ),
    ]
