# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0005_auto_20161006_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='internal_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
