# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0006_auto_20161007_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='strain_slug',
            field=models.SlugField(blank=True, max_length=611, null=True),
        ),
    ]
