# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 10:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.search.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0008_auto_20161008_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Maximum file size allowed is 10Mb', max_length=255, upload_to=web.search.models.upload_image_to, validators=[web.search.models.validate_image])),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.Strain')),
            ],
        ),
    ]
