# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 20:58
from __future__ import unicode_literals

from django.db import migrations


def populate_default_effects(apps, schema_editor):
    Effect = apps.get_model("search", "Effect")

    defaults = [
        {'effect_type': 'effect', 'data_name': 'happy', 'display_name': 'Happy'},
        {'effect_type': 'effect', 'data_name': 'uplifted', 'display_name': 'Uplifted'},
        {'effect_type': 'effect', 'data_name': 'stimulated', 'display_name': 'Stimulated'},
        {'effect_type': 'effect', 'data_name': 'energetic', 'display_name': 'Energetic'},
        {'effect_type': 'effect', 'data_name': 'creative', 'display_name': 'Creative'},
        {'effect_type': 'effect', 'data_name': 'focused', 'display_name': 'Focused'},
        {'effect_type': 'effect', 'data_name': 'relaxed', 'display_name': 'Relaxed'},
        {'effect_type': 'effect', 'data_name': 'sleepy', 'display_name': 'Sleepy'},
        {'effect_type': 'effect', 'data_name': 'talkative', 'display_name': 'Talkative'},
        {'effect_type': 'effect', 'data_name': 'euphoric', 'display_name': 'Euphoric'},
        {'effect_type': 'effect', 'data_name': 'hungry', 'display_name': 'Hungry'},
        {'effect_type': 'effect', 'data_name': 'tingly', 'display_name': 'Tingly'},
        {'effect_type': 'effect', 'data_name': 'good_humored', 'display_name': 'Good Humored'},

        {'effect_type': 'benefit', 'data_name': 'reduce_stress', 'display_name': 'Reduce Stress'},
        {'effect_type': 'benefit', 'data_name': 'help_depression', 'display_name': 'Help Depression'},
        {'effect_type': 'benefit', 'data_name': 'relieve_pain', 'display_name': 'Relieve Pain'},
        {'effect_type': 'benefit', 'data_name': 'reduce_fatigue', 'display_name': 'Reduce Fatigue'},
        {'effect_type': 'benefit', 'data_name': 'reduce_headaches', 'display_name': 'Reduce Headaches'},
        {'effect_type': 'benefit', 'data_name': 'help_muscles_spasms', 'display_name': 'Help Muscles Spasms'},
        {'effect_type': 'benefit', 'data_name': 'lower_eye_pressure', 'display_name': 'Lower Eye Pressure'},
        {'effect_type': 'benefit', 'data_name': 'reduce_nausea', 'display_name': 'Reduce Nausea'},
        {'effect_type': 'benefit', 'data_name': 'reduce_inflammation', 'display_name': 'Reduce Inflammation'},
        {'effect_type': 'benefit', 'data_name': 'relieve_cramps', 'display_name': 'Relieve Cramps'},
        {'effect_type': 'benefit', 'data_name': 'help_with_seizures', 'display_name': 'Help With Seizures'},
        {'effect_type': 'benefit', 'data_name': 'restore_appetite', 'display_name': 'Restore Appetite'},
        {'effect_type': 'benefit', 'data_name': 'help_with_insomnia', 'display_name': 'Help With Insomnia'},

        {'effect_type': 'side_effect', 'data_name': 'anxiety', 'display_name': 'Anxiety'},
        {'effect_type': 'side_effect', 'data_name': 'dry_mouth', 'display_name': 'Dry Mouth'},
        {'effect_type': 'side_effect', 'data_name': 'paranoia', 'display_name': 'Paranoia'},
        {'effect_type': 'side_effect', 'data_name': 'headache', 'display_name': 'Headache'},
        {'effect_type': 'side_effect', 'data_name': 'dizziness', 'display_name': 'Dizziness'},
        {'effect_type': 'side_effect', 'data_name': 'dry_eyes', 'display_name': 'Dry Eyes'},
    ]

    for entry in defaults:
        e = Effect(effect_type=entry.get('effect_type'),
                   data_name=entry.get('data_name'),
                   display_name=entry.get('display_name'))
        e.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0010_auto_20161020_2051'),
    ]

    operations = [
        migrations.RunPython(populate_default_effects, reverse),
    ]
