# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 20:31
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0011_import_default_effects'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varieties', django.contrib.postgres.fields.jsonb.JSONField(max_length=250)),
                ('effects', django.contrib.postgres.fields.jsonb.JSONField(max_length=1000)),
                ('benefits', django.contrib.postgres.fields.jsonb.JSONField(max_length=1000)),
                ('side_effects', django.contrib.postgres.fields.jsonb.JSONField(max_length=1000)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
