# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-13 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20161111_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strainreview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainreview',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainreview',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
