# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-20 13:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0016_auto_20161114_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStrainReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('effects', 'Effects'), ('benefits', 'Benefits'), ('side_effects', 'Side Effects')], max_length=20)),
                ('effects', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.Strain')),
            ],
        ),
    ]
