# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-20 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_userstrainreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrainreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=20),
        ),
    ]
