# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_userstrainreview_removed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrainreview',
            name='created_by_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userstrainreview',
            name='last_modified_by_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
