# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0020_auto_20161120_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('strain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search.Strain')),
            ],
        ),
    ]
