# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_userfavoritestrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritestrain',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.Strain'),
        ),
    ]
