# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 22:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_auto_20161122_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstrainreview',
            name='effect_type',
        ),
        migrations.AddField(
            model_name='userstrainreview',
            name='benefits',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='userstrainreview',
            name='benefits_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstrainreview',
            name='effects_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstrainreview',
            name='side_effects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='userstrainreview',
            name='side_effects_changed',
            field=models.BooleanField(default=False),
        ),
    ]
