# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_auto_20161125_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='strainimage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
