# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 20:57
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def change_strains_slug_names(apps, schema_editor):
    Strain = apps.get_model("search", "Strain")

    for strain in Strain.objects.all():
        strain.strain_slug = '{0}-strain'.format(slugify(strain.name))
        strain.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0025_strainimage_is_approved'),
    ]

    operations = [
        migrations.RunPython(change_strains_slug_names, reverse),
    ]
