# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_rename_strain_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='about',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description'),
        ),
    ]
