# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_auto_20170117_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='removed_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='removed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
