# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-02 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_auto_20170123_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
