# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 20:57
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def insert_default_flavors(apps, schema_editor):
    Flavor = apps.get_model("search", "Flavor")

    defaults = [
        {'display_name': 'Ammonia'},
        {'display_name': 'Apple'},
        {'display_name': 'Apricot'},
        {'display_name': 'Berry'},
        {'display_name': 'Blue Cheese'},
        {'display_name': 'Blueberry'},
        {'display_name': 'Buttery'},
        {'display_name': 'Cheese'},
        {'display_name': 'Chemical'},
        {'display_name': 'Chestnut'},
        {'display_name': 'Citrus'},
        {'display_name': 'Coffee'},
        {'display_name': 'Diesel'},
        {'display_name': 'Earthy'},
        {'display_name': 'Flowery'},
        {'display_name': 'Grape'},
        {'display_name': 'Grapefruit'},
        {'display_name': 'Herbal'},
        {'display_name': 'Honey'},
        {'display_name': 'Lavender'},
        {'display_name': 'Lemon'},
        {'display_name': 'Lime'},
        {'display_name': 'Mango'},
        {'display_name': 'Menthol'},
        {'display_name': 'Minty'},
        {'display_name': 'Nutty'},
        {'display_name': 'Orange'},
        {'display_name': 'Peach'},
        {'display_name': 'Pear'},
        {'display_name': 'Pepper'},
        {'display_name': 'Pine'},
        {'display_name': 'Pineapple'},
        {'display_name': 'Plum'},
        {'display_name': 'Pungent'},
        {'display_name': 'Rose'},
        {'display_name': 'Sage'},
        {'display_name': 'Skunk'},
        {'display_name': 'Spicy Herbal'},
        {'display_name': 'Strawberry'},
        {'display_name': 'Sweet'},
        {'display_name': 'Tar'},
        {'display_name': 'Tea'},
        {'display_name': 'Tobacco'},
        {'display_name': 'Tree Fruit'},
        {'display_name': 'Tropical'},
        {'display_name': 'Vanilla'},
        {'display_name': 'Violet'},
        {'display_name': 'Woody'},
    ]

    for entry in defaults:
        f = Flavor(display_name=entry.get('display_name'), data_name=slugify(entry.get('display_name')))
        f.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0030_flavor'),
    ]

    operations = [
        migrations.RunPython(insert_default_flavors, reverse),
    ]
