# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_insert_default_flavors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='data_name',
            field=models.SlugField(help_text='This will be slugified automatically from Display Name', max_length=100),
        ),
    ]
