# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 20:57
from __future__ import unicode_literals

from django.db import migrations


def change_strains_flavor_keys(apps, schema_editor):
    Strain = apps.get_model("search", "Strain")

    for strain in Strain.objects.all():
        flavor = strain.flavor
        new_flavor = {}

        for key in flavor:
            new_key = key

            if key == 'blue_cheese':
                new_key = 'blue-cheese'

            if key == 'spicy_herbal':
                new_key = 'spicy-herbal'

            if key == 'tree_fruit':
                new_key = 'tree-fruit'

            new_flavor[new_key] = flavor[key]

        strain.flavor = new_flavor
        strain.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0032_auto_20170217_0649'),
    ]

    operations = [
        migrations.RunPython(change_strains_flavor_keys, reverse),
    ]
