# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 20:57
from __future__ import unicode_literals

from django.db import migrations


def update(apps, schema_editor):
    Strain = apps.get_model("search", "Strain")

    for strain in Strain.objects.all():
        strain.side_effects["spacey"] = 0
        strain.side_effects["lazy"] = 0
        strain.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0034_auto_20170310_1653'),
    ]

    operations = [
        migrations.RunPython(update, reverse),
    ]
