# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-21 17:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0036_add_new_side_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='side_effects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'anxiety': 0, 'dizziness': 0, 'dry_eyes': 0, 'dry_mouth': 0, 'headache': 0, 'lazy': 0, 'paranoia': 0, 'spacey': 0}),
        ),
        migrations.AlterField(
            model_name='strainreview',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
