# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-22 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms
import web.search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_auto_20170321_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, help_text='Maximum file size allowed is 10Mb', max_length=255, upload_to=web.common.models.upload_to, validators=[web.common.models.validate_image]),
        ),
        migrations.AddField(
            model_name='strain',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=3072),
        ),
        migrations.AddField(
            model_name='strain',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=3072),
        ),
    ]
