# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_auto_20170822_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='strainimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
