# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0040_strainimage_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strainreview',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='strainreview',
            name='last_modified_date',
            field=models.DateTimeField(),
        ),
    ]
