# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0041_auto_20171228_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strainimage',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='search.Strain'),
        ),
    ]
