# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-02-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0045_auto_20180212_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='you_may_also_like_exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='strain',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
