# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-02-23 14:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0046_auto_20180214_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='cannabinoids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'CBC': 0, 'CBD': 0, 'CBG': 0, 'CBN': 0, 'THC': 0, 'THCA': 0, 'THCV': 0}),
        ),
        migrations.AddField(
            model_name='strain',
            name='terpenes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'camphene': 0, 'carene': 0, 'caryophyllene': 0, 'geraniol': 0, 'humulene': 0, 'limonene': 0, 'linalool': 0, 'myrcene': 0, 'ocimene': 0, 'phellandrene': 0, 'pinene': 0, 'pulegone': 0, 'sabinene': 0, 'terpineol': 0, 'terpinolene': 0}),
        ),
    ]
