# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import web.search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0049_auto_20180413_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='is_clean',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='is_indoor',
        ),
        migrations.AlterField(
            model_name='strainimage',
            name='image',
            field=models.ImageField(help_text='Maximum file size allowed is 10Mb', max_length=255, upload_to=web.search.models.upload_image_to, validators=[web.search.models.validate_image]),
        ),
    ]
