# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-24 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0050_auto_20180417_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strainimage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainimage',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='search.Strain'),
        ),
        migrations.AlterField(
            model_name='strainrating',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainrating',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainrating',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Strain'),
        ),
        migrations.AlterField(
            model_name='strainreview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainreview',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainreview',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Strain'),
        ),
        migrations.AlterField(
            model_name='userfavoritestrain',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfavoritestrain',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Strain'),
        ),
    ]
