# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0051_auto_20180424_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strainreview',
            name='review',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
