# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models


def change_strain_default_values(apps, schema_editor):
    Strain = apps.get_model("search", "Strain")
    Strain.objects.all().update(growing_method=None, lighting=None, nutrient_base=None)


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0054_auto_20180510_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='growing_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Indoor Soil'), (2, 'Indoor Hydro'), (3, 'Indoor Coco'), (4, 'Outdoor'), (5, 'Greenhouse'), (6, 'Aquaponics')], null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='lighting',
            field=models.IntegerField(blank=True, choices=[(1, 'Natural Light Schedule'), (2, 'HID'), (3, 'LED'), (4, 'Double Ended'), (5, 'Halogen')], null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='nutrient_base',
            field=models.IntegerField(blank=True, choices=[(1, 'Synthetic Nutrients'), (2, 'Organic Nutrients'), (3, 'Blended Nutrients')], null=True),
        ),
        migrations.RunPython(change_strain_default_values, migrations.RunPython.noop)
    ]
