# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.businesses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Maximum file size allowed is 5Mb', max_length=255, upload_to=web.businesses.models.upload_business_image_to, validators=[web.businesses.models.validate_business_image])),
                ('certified_legal_compliance', models.BooleanField(default=False)),
                ('dispensary', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('grow_house', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_created_by', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='business_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('dispensary', 'Dispensary'), ('delivery', 'Delivery'), ('grow_house', 'Grow House')], max_length=15)),
                ('street1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('ext', models.CharField(blank=True, max_length=5, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('mon_open', models.CharField(blank=True, max_length=10, null=True)),
                ('mon_close', models.CharField(blank=True, max_length=10, null=True)),
                ('tue_open', models.CharField(blank=True, max_length=10, null=True)),
                ('tue_close', models.CharField(blank=True, max_length=10, null=True)),
                ('wed_open', models.CharField(blank=True, max_length=10, null=True)),
                ('wed_close', models.CharField(blank=True, max_length=10, null=True)),
                ('thu_open', models.CharField(blank=True, max_length=10, null=True)),
                ('thu_close', models.CharField(blank=True, max_length=10, null=True)),
                ('fri_open', models.CharField(blank=True, max_length=10, null=True)),
                ('fri_close', models.CharField(blank=True, max_length=10, null=True)),
                ('sat_open', models.CharField(blank=True, max_length=10, null=True)),
                ('sat_close', models.CharField(blank=True, max_length=10, null=True)),
                ('sun_open', models.CharField(blank=True, max_length=10, null=True)),
                ('sun_close', models.CharField(blank=True, max_length=10, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businesses.Business')),
            ],
        ),
    ]
