# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='users',
            field=models.ManyToManyField(related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='fri_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='fri_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='mon_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='mon_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='sat_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='sat_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='sun_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='sun_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='thu_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='thu_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='tue_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='tue_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='wed_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='wed_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
