# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20161026_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='trial_period_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
