# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_auto_20161104_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
