# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businesslocation_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='location_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
