# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_usersearch'),
        ('businesses', '0007_businesslocation_location_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_gram', models.FloatField(blank=True, max_length=50, null=True)),
                ('price_eighth', models.FloatField(blank=True, max_length=50, null=True)),
                ('price_quarter', models.FloatField(blank=True, max_length=50, null=True)),
                ('price_half', models.FloatField(blank=True, max_length=50, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businesses.BusinessLocation')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.Strain')),
            ],
        ),
    ]
