# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_auto_20161106_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslocation',
            name='removed',
        ),
    ]
