# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_remove_businesslocation_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
