# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_businesslocationmenuitem'),
        ('businesses', '0010_auto_20161107_1714'),
    ]

    operations = [
    ]
