# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_businesslocationmenuitem_removed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='delivery_radius',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
