# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-15 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import web.businesses.models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_businesslocation_delivery_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='is_business_verified',
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[web.businesses.models.phone_number_validator]),
        ),
    ]
