# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 20:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_auto_20161115_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='location_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, max_length=20000, verbose_name='Location Raw JSON'),
        ),
    ]
