# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-10 10:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_auto_20161209_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='location_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, max_length=20000, null=True, verbose_name='Location Raw JSON'),
        ),
    ]
