# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-10 18:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_auto_20161210_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='location_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, max_length=20000, verbose_name='Location Raw JSON'),
        ),
    ]
