# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import web.businesses.models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_auto_20161210_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 5Mb', max_length=255, upload_to=web.businesses.models.upload_business_location_image_to, validators=[web.businesses.models.validate_business_image]),
        ),
    ]
