# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0024_generate_slug_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='category',
            field=models.CharField(choices=[('dispensary', 'Dispensary'), ('delivery', 'Delivery')], default='dispensary', help_text='Warning: changing the category will change the URL of this location', max_length=20),
        ),
    ]
