# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-17 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0025_businesslocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='about',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
