# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0026_auto_20170117_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='about',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
