# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 19:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0027_auto_20170118_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='location_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, max_length=20000, null=True, verbose_name='Location Raw JSON'),
        ),
    ]
