# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 22:41
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def generate_slug_names(apps, schema_editor):
    BusinessLocation = apps.get_model("businesses", "BusinessLocation")

    for l in BusinessLocation.objects.all():
        slugified_name = slugify('{0} {1}'.format(l.location_name, l.city))

        if not BusinessLocation.objects.filter(slug_name=slugified_name).exists():
            l.slug_name = slugified_name
        else:
            for x in range(1, 1000):
                new_slug_name = '{0}-{1}'.format(slugified_name, x)
                if not BusinessLocation.objects.filter(slug_name=new_slug_name).exists():
                    l.slug_name = new_slug_name
                    break
        l.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('businesses', '0027_auto_20170118_2039'),
    ]

    operations = [
        migrations.RunPython(generate_slug_names, reverse),
    ]
