# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0028_auto_20170123_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
