# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0029_businesslocation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslocation',
            name='active',
        ),
    ]
