# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0030_remove_businesslocation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='location_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='slug_name',
            field=models.SlugField(blank=True, help_text='This will be automatically generated from a location name when created', max_length=611, null=True),
        ),
    ]
