# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0031_auto_20170123_2032'),
        ('businesses', '0028_change_location_slug_names'),
    ]

    operations = [
    ]
