# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0033_auto_20170202_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='city_slug',
            field=models.SlugField(blank=True, help_text='This will be automatically generated from a city when updated', max_length=611, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='category',
            field=models.CharField(choices=[('dispensary', 'Dispensary'), ('delivery', 'Delivery')], default='dispensary', max_length=20),
        ),
    ]
