# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-13 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0035_add_city_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=2)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businesses.State'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='city_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='businesses.City'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='state_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='businesses.State'),
        ),
    ]
