# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0037_create_states_and_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='description2',
            field=models.TextField(blank=True, help_text='This will be used on /dispensaries/{state} page as a state description', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(blank=True, help_text='This will be used on /dispensaries page as a state description', null=True),
        ),
    ]
