# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0038_auto_20170314_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='full_name_slug',
            field=models.SlugField(blank=True, help_text='This will be automatically changed from a city full name when updated', max_length=150, null=True),
        ),
    ]
