# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 22:41
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def update(apps, schema_editor):
    City = apps.get_model("businesses", "City")

    for c in City.objects.all():
        c.full_name_slug = slugify(c.full_name)
        c.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('businesses', '0039_city_full_name_slug'),
    ]

    operations = [
        migrations.RunPython(update, reverse),
    ]
