# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0040_update_cities_full_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='businesslocation',
            unique_together=set([('state_fk', 'city_fk', 'slug_name')]),
        ),
    ]
