# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-12 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0044_auto_20170822_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True, help_text='Display this state on the dispensaries list page?'),
        ),
    ]
