# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-11 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0045_state_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='account_type',
            field=models.CharField(choices=[('house_account', 'House Account'), ('claimed_account_free', 'Claimed Account Free'), ('paid_account', 'Paid Account')], default='house_account', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='last_payment_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='last_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='businesses.Business'),
        ),
    ]
