# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0046_auto_20171211_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
    ]
