# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-05 13:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0048_auto_20171213_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocation',
            name='grow_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'indoor': False, 'organic': False, 'pesticide_free': False}, null=True),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='category',
            field=models.CharField(choices=[('dispensary', 'Dispensary'), ('delivery', 'Delivery'), ('grow_house', 'Grow House')], default='dispensary', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesslocationmenuitem',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_items', to='search.Strain'),
        ),
    ]
