# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-10 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0049_auto_20180105_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowerDispensaryPartnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grower_partnerships', to='businesses.BusinessLocation')),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_partnerships', to='businesses.BusinessLocation')),
            ],
        ),
    ]
