# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-17 11:06
from __future__ import unicode_literals

from datetime import date

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    default_menu_update = date(year=2017, month=8, day=13)
    apps.get_model('businesses', 'BusinessLocation').objects.update(menu_updated_date=default_menu_update)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0050_growerdispensarypartnership'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationMenuUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='menu_updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='city_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_locations', to='businesses.City'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='state_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_locations', to='businesses.State'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='businesses.State'),
        ),
        migrations.AddField(
            model_name='businesslocationmenuupdate',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_updates', to='businesses.BusinessLocation'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
