# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-19 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0051_auto_20180117_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationMenuUpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('served', models.BooleanField(default=False)),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.BusinessLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
