# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-24 13:19
from __future__ import unicode_literals

from datetime import date
from random import randint

from django.db import migrations


def forwards_func(apps, schema_editor):
    for location in apps.get_model('businesses', 'BusinessLocation').objects.iterator():
        location.menu_updated_date = date(year=2018, month=1, day=randint(3, 20))
        location.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0052_businesslocationmenuupdaterequest'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
