# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0053_auto_20180124_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocationmenuupdaterequest',
            name='secret_key',
            field=models.TextField(null=True),
        ),
    ]
