# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-02-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0055_auto_20180126_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationPermanentlyRemoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_slug', models.TextField()),
                ('slug_name', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
        migrations.AlterField(
            model_name='businesslocationmenuitem',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.BusinessLocation'),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.BusinessLocation'),
        ),
        migrations.AlterField(
            model_name='userfavoritelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.BusinessLocation'),
        ),
    ]
