# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0056_auto_20180223_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslocationmenuitem',
            name='growing_method',
            field=models.IntegerField(choices=[(1, 'Indoor Soil'), (2, 'Indoor Hydro'), (3, 'Indoor Coco'), (4, 'Outdoor'), (5, 'Greenhouse'), (6, 'Aquaponics')], default=1),
        ),
        migrations.AddField(
            model_name='businesslocationmenuitem',
            name='lighting',
            field=models.IntegerField(choices=[(1, 'Natural Light Schedule'), (2, 'HID'), (3, 'LED'), (4, 'Double Ended'), (5, 'Halogen')], default=1),
        ),
        migrations.AddField(
            model_name='businesslocationmenuitem',
            name='nutrient_base',
            field=models.IntegerField(choices=[(1, 'Synthetic Nutrients'), (2, 'Organic Nutrients'), (3, 'Blended Nutrients')], default=1),
        ),
    ]
