# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-24 15:53
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import migrations


def migrate_to_permanently_removed_model(apps, schema_editor):
    BusinessLocationPermanentlyRemoved = apps.get_model('businesses', 'BusinessLocationPermanentlyRemoved')
    PermanentlyRemoved = apps.get_model('system', 'PermanentlyRemoved')

    for location in BusinessLocationPermanentlyRemoved.objects.iterator():
        PermanentlyRemoved.objects.create(
            status=410,
            url=reverse('businesses:dispensary_info', args=(location.state, location.city_slug, location.slug_name)))


def migrate_to_business_location_permanently_removed(apps, schema_editor):
    BusinessLocationPermanentlyRemoved = apps.get_model('businesses', 'BusinessLocationPermanentlyRemoved')
    PermanentlyRemoved = apps.get_model('system', 'PermanentlyRemoved')

    locations = PermanentlyRemoved.objects.filter(status=410)
    for instance in locations:
        state, city_slug, slug_name, _ = instance.url.split('/')[-4:]
        BusinessLocationPermanentlyRemoved.objects.create(
            city_slug=city_slug,
            slug_name=slug_name,
            state=state
        )
    locations.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0057_auto_20180417_1840'),
        ('system', '0007_permanentlyremoved'),
    ]

    operations = [
        migrations.RunPython(
            migrate_to_permanently_removed_model,
            migrate_to_business_location_permanently_removed
        ),
        migrations.DeleteModel(
            name='BusinessLocationPermanentlyRemoved',
        ),
    ]
