# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-24 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0058_delete_businesslocationpermanentlyremoved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocationmenuitem',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='search.Strain'),
        ),
    ]
