# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-25 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0059_auto_20180424_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationreview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='last_modified_date',
            field=models.DateTimeField(),
        ),
    ]
