# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-06 05:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0060_auto_20180425_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOutOfStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=1)),
                ('start_timer', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.BusinessLocationMenuItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('menu_item', '-created'),
            },
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='category',
            field=models.CharField(choices=[('dispensary', 'Dispensary'), ('delivery', 'Delivery'), ('grow_house', 'Cultivator')], default='dispensary', max_length=20),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='last_modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
