# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-07 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0061_auto_20180507_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportoutofstock',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='reportoutofstock',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='businesses.BusinessLocationMenuItem'),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
