# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-10 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0062_auto_20180507_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavoritelocation',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='businesslocationmenuitem',
            name='growing_method',
        ),
        migrations.RemoveField(
            model_name='businesslocationmenuitem',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='businesslocationmenuitem',
            name='nutrient_base',
        ),
    ]
