# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-11 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0057_populate_flavors'),
        ('businesses', '0063_auto_20180510_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationGrownStrainItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grown_strains', to='businesses.BusinessLocation')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grown_items', to='search.Strain')),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.Business'),
        ),
        migrations.AlterField(
            model_name='userfavoritelocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
