# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-18 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0064_auto_20181216_1931'),
        ('businesses', '0065_auto_20181215_1200'),
    ]

    operations = [
    ]
