# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-30 08:22
from __future__ import unicode_literals

from django.db import migrations


def populate_meta(apps, schema_editor):
    BusinessLocation = apps.get_model('businesses', 'BusinessLocation')
    BusinessLocation.objects.all().update(meta_title='', og_title='', og_description='')


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0066_merge'),
    ]

    operations = [
        migrations.RunPython(populate_meta, migrations.RunPython.noop)
    ]
