---

- name: Install all packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - build-essential
    - gettext
    - python3-dev
    - python3-pip
    - ipython3
    - htop
    - git
    - nginx
    - fail2ban
    - openssl
    - libssl-dev
    - libssl-doc
    - bash
    # psycopg2 dependencies
    - libpq-dev
    # pillow dependencies
    - zlib1g-dev
    - libtiff5-dev
    - libjpeg8-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    # django extensions
    - graphviz-dev
    # GeoDjango dependencies
    - binutils
    - libproj-dev
    - gdal-bin
  tags: packages

- name: Upgrade pip3
  pip: name=pip state=latest executable=pip3
  tags: packages

- name: Upgrade pip2
  pip: name=pip state=latest executable=pip2
  tags: packages
