---

- include: install_packages.yml
  tags: packages

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_sshd_config.yml
  tags: config

- include: setup_fail2ban.yml
  tags: config

- include: setup_ufw.yml
  tags: config

#- include: install_node.yml
#  tags: packages

- include: setup_git_repo.yml
  tags: deploy

#- include: frontend_build.yml
#  tags: deploy

- include: setup_django_app.yml
  tags: deploy

- include: set_file_permissions.yml
  tags: deploy

