---

- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  notify: restart application

- name: Ensure that the application file permissions are set properly
  file: path={{ project_root }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  notify: restart application

- name: Create the django log file
  file: path={{ project_root }}/srx_error.log
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0664
        state=touch