---

#- name: Install packages required by the Django app inside virtualenv
#  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }} executable=pip3

# TODO test with runnable django instance

#- name: Run Django database migrations
#  django_manage:
#    command: migrate
#    app_path: "{{ project_path }}"
#    virtualenv: "{{ virtualenv_path }}"
#    settings: "{{ django_settings_file }}"
#  environment: "{{ django_environment }}"
#  when: run_django_db_migrations is defined and run_django_db_migrations
#  tags: django.migrate
#
#- name: Run Django collectstatic
#  django_manage:
#    command: collectstatic
#    app_path: "{{ project_path }}"
#    virtualenv: "{{ virtualenv_path }}"
#    settings: "{{ django_settings_file }}"
#  environment: "{{ django_environment }}"
#  when: run_django_collectstatic is defined and run_django_collectstatic
#  tags: django.collectstatic

- name: Create env var file
  template: src=env_vars.j2
            dest={{ project_path }}/.env
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes
  tags: deploy