# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-20 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event',
        ),
    ]
