# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Birth Day'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_month',
            field=models.CharField(blank=True, max_length=20, verbose_name='Birth Month'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Birth Year'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10,
                                   verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip Code'),
        ),
    ]
