# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 19:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160925_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwResetLink',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
