# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-06 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161023_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('lat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('lng', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('location_raw', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Location Raw JSON')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
