# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20161206_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='street1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
    ]
