# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 17:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20161207_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='location_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, max_length=20000, verbose_name='Location Raw JSON'),
        ),
    ]
