# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20161208_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='lat',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lng',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
