# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20161209_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proximity',
            field=models.FloatField(null=True, verbose_name='Proximity'),
        ),
    ]
