# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_proximity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
