# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-14 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
