# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-11 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20171214_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_search_history',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
