# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-19 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_display_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Name of User'),
            preserve_default=False,
        ),
    ]
