# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 17:55
from __future__ import unicode_literals

from django.db import migrations


def insert_max_delivery_radius(apps, schema_editor):
    SystemProperty = apps.get_model("system", "SystemProperty")
    system_property = SystemProperty(name='max_delivery_radius', value='50')
    system_property.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0002_auto_20161129_1603'),
    ]

    operations = [
        migrations.RunPython(insert_max_delivery_radius, reverse),
    ]
