# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 22:41
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def update(apps, schema_editor):
    SystemProperty = apps.get_model("system", "SystemProperty")
    system_property = SystemProperty(name='auto_email_verification_for_business', value='false')
    system_property.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0004_auto_20161214_1749'),
    ]

    operations = [
        migrations.RunPython(update, reverse),
    ]
