# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_insert_new_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemproperty',
            name='name',
            field=models.CharField(choices=[('rating_recalculation_size', 'Rating Recalculation Size'), ('max_delivery_radius', 'Max Delivery/Proximity Radius'), ('auto_email_verification_for_business', 'Auto Email Verification for Business Users')], max_length=50, unique=True),
        ),
    ]
