# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-24 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20170807_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentlyRemoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('redirect_url', models.CharField(blank=True, max_length=255)),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
