# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-04 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20180425_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permanentlyremoved',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='permanentlyremoved',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 4, 13, 10, 45, 695421, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
