# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms
import web.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20180504_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPageMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, default='Strains Web', max_length=3072, verbose_name='Page Title')),
                ('meta_desc', models.CharField(blank=True, default="StrainRx is the premiere online source for strain intelligence. We help cannabis users find the perfect strain that's ideally suited for their needs.", max_length=3072, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=3072, verbose_name='Meta Keywords')),
                ('social_image', django_resized.forms.ResizedImageField(blank=True, help_text='Maximum file size allowed is 10Mb', max_length=255, upload_to=web.common.models.upload_to, validators=[web.common.models.validate_image])),
                ('og_type', models.CharField(blank=True, choices=[('article', 'Article'), ('website', 'Website')], default='website', help_text='Use Article for generic pages.', max_length=25, verbose_name='Resource type property="og:type"')),
                ('og_title', models.CharField(blank=True, default='Cannabis Intelligence Platform - StrainRx', max_length=255, verbose_name='Resource title property="og:title"')),
                ('og_description', models.CharField(blank=True, default="StrainRx is a tool to identify and locate cannabis strains with optimal effects and benefits, based on a user's personal preference and need.", max_length=255, verbose_name='Resource description property="og:description"')),
                ('fb_app_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook App ID property="fb:app_id"')),
                ('twitter_card', models.CharField(blank=True, choices=[('summary', 'Summary Card'), ('summary_large_image', 'Summary Card with Large Image'), ('product', 'Product'), ('photo', 'Photo'), ('player', 'Player'), ('app', 'App')], default='summary_large_image', help_text='The card type, which will be one of "summary", "summary_large_image", "app", or "player".', max_length=25, verbose_name='Resource type name="twitter:card"')),
                ('twitter_author', models.CharField(blank=True, default='@StrainRx', max_length=255, verbose_name='Author Twitter Account name="twitter:author"')),
                ('twitter_site', models.CharField(blank=True, default='@StrainRx', max_length=255, verbose_name='Website Twitter Account name="twitter:site"')),
                ('meta_tags', models.TextField(blank=True, help_text='Use this field to insert meta tags in html which you may need.', verbose_name='Meta tags')),
                ('path', models.CharField(db_index=True, help_text="This should be an absolute path, excluding the domain name. Example: '/foo/bar/'.", max_length=200, unique=True, verbose_name='Path')),
            ],
            options={
                'ordering': ('path',),
                'verbose_name': 'SEO metadata',
                'verbose_name_plural': 'SEO metadata',
            },
        ),
    ]
