# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_toppagemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppagemetadata',
            name='og_description',
            field=models.CharField(blank=True, help_text='Leave the field blank if it should be equal to "Meta Description" field value.', max_length=3072, verbose_name='Resource description property="og:description"'),
        ),
        migrations.AlterField(
            model_name='toppagemetadata',
            name='og_title',
            field=models.CharField(blank=True, help_text='Leave the field blank if it should be equal to "Page Title" field value.', max_length=3072, verbose_name='Resource title property="og:title"'),
        ),
    ]
