from django.conf.urls import url

from web.search.api.views import *

urlpatterns = [
    url(
        regex=r'^effect/(?P<effect_type>[a-z_]+)$',
        view=StrainEffectView.as_view(),
        name='effect_type'
    ),
    url(
        regex=r'^flavors$',
        view=StrainFlavorView.as_view(),
        name='flavors'
    ),
    url(
        regex=r'^strains/(?P<strain_variety>.+)$',
        view=StrainsListByVarietyView.as_view(),
        name='strains_list'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/images/$',
        view=StrainImagesView.as_view(),
        name='strain_images'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/rate',
        view=StrainRateView.as_view(),
        name='strain_rate'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/details',
        view=StrainDetailsView.as_view(),
        name='strain_details'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/deliveries',
        view=StrainDeliveriesView.as_view(),
        name='strain_deliveries'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/reviews',
        view=StrainReviewsView.as_view(),
        name='strain_reviews'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/ratings',
        view=StrainRatingsView.as_view(),
        name='strain_ratings'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/favorite',
        view=StrainFavoriteView.as_view(),
        name='strain_favorite'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/srx_score',
        view=StrainSRXScoreView.as_view(),
        name='strain_srx_score'
    ),
    url(
        regex=r'^strain/(?P<strain_id>[0-9]+)/also_like',
        view=StrainAlsoLikeView.as_view(),
        name='strain_also_like'
    ),
    url(
        regex=r'^strain/lookup/$',
        view=StrainLookupView.as_view(),
        name='strain_lookup'
    ),
    url(
        regex=r'^strain',
        view=StrainSearchWizardView.as_view(),
        name='strain'
    ),
    url(
        regex=r'^result/$',
        view=StrainSearchResultsView.as_view(),
        name='strain_result'
    ),
]
