---
# see https://github.com/jcalazan/ansible-django-stack for hints and examples
- name: Provision a {{ application_name }} web server
  hosts: webservers
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/django_{{ env }}.yml
    - env_vars/{{ env }}.yml
  roles:
    - web
    - nginx
