# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import djangocms_text_ckeditor.fields
import web.articles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('summary', models.CharField(blank=True, max_length=3072)),
                ('meta_desc', models.CharField(blank=True, max_length=3072)),
                ('source_id', models.CharField(blank=True, max_length=1024)),
                ('meta_keywords', models.CharField(blank=True, max_length=3072)),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('source', models.CharField(max_length=2068, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('featured', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawl_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, help_text='Maximum file size allowed is 5Mb', max_length=255, upload_to=web.articles.models.upload_to, validators=[web.articles.models.validate_image])),
                ('image_caption', models.CharField(blank=True, max_length=1024)),
                ('slug', models.SlugField(blank=True, default=None, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default=None, max_length=1024, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='Category'),
        ),
    ]
