# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-07 18:54
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import web.articles.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='crawl_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, help_text='Maximum file size allowed is 10Mb', max_length=255, upload_to=web.articles.models.upload_to, validators=[web.articles.models.validate_image]),
        ),
    ]
