# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-09 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170807_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_approved',
        ),
    ]
