# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-18 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_is_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_page',
            field=models.BooleanField(default=False),
        ),
    ]
