# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import web.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180424_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fb_app_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook App ID property="fb:app_id"'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_tags',
            field=models.TextField(blank=True, help_text='Use this field to insert meta tags in html which you may need.', verbose_name='Meta tags'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, default='Strains Web', max_length=3072, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, default="StrainRx is a tool to identify and locate cannabis strains with optimal effects and benefits, based on a user's personal preference and need.", max_length=255, verbose_name='Resource description property="og:description"'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, default='Cannabis Intelligence Platform - StrainRx', max_length=255, verbose_name='Resource title property="og:title"'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_type',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('website', 'Website')], default='website', help_text='Use Article for generic pages.', max_length=25, verbose_name='Resource type property="og:type"'),
        ),
        migrations.AddField(
            model_name='article',
            name='social_image',
            field=django_resized.forms.ResizedImageField(blank=True, help_text='Maximum file size allowed is 10Mb', max_length=255, upload_to=web.common.models.upload_to, validators=[web.common.models.validate_image]),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_author',
            field=models.CharField(blank=True, default='@StrainRx', max_length=255, verbose_name='Author Twitter Account name="twitter:author"'),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_card',
            field=models.CharField(blank=True, choices=[('summary', 'Summary Card'), ('summary_large_image', 'Summary Card with Large Image'), ('product', 'Product'), ('photo', 'Photo'), ('player', 'Player'), ('app', 'App')], default='summary_large_image', help_text='The card type, which will be one of "summary", "summary_large_image", "app", or "player".', max_length=25, verbose_name='Resource type name="twitter:card"'),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_site',
            field=models.CharField(blank=True, default='@StrainRx', max_length=255, verbose_name='Website Twitter Account name="twitter:site"'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_desc',
            field=models.CharField(blank=True, default="StrainRx is the premiere online source for strain intelligence. We help cannabis users find the perfect strain that's ideally suited for their needs.", max_length=3072, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=3072, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='articles.Category'),
        ),
    ]
