# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-30 10:23
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def populate_meta(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    Article.objects.all().update(meta_title=F('title'), og_title=F('title'), og_description=F('meta_desc'))


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_merge'),
    ]

    operations = [
        migrations.RunPython(populate_meta, migrations.RunPython.noop)
    ]
