# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-31 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20181230_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_desc',
            field=models.CharField(blank=True, default="StrainRx is the premiere online source for strain intelligence. We help cannabis users find the perfect strain that's ideally suited for their needs.", help_text='Leave the field blank to display the default description as `StrainRx brings you the most up to date menu and the latest deals from { location_name } in { city }`', max_length=3072, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, default='Strains Web', help_text='Leave the field blank to display the default title as `{ location_name } Dispensary in { city }, { street1 }` for dispensary page and `{ location_name } Cultivator in { city }, { street1 }` for cultivator page.', max_length=3072, verbose_name='Page Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, help_text='Leave the field blank if it should be equal to "Meta Description" field value.', max_length=3072, verbose_name='Resource description property="og:description"'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, help_text='Leave the field blank if it should be equal to "Page Title" field value.', max_length=3072, verbose_name='Resource title property="og:title"'),
        ),
    ]
